"use client";
import {useEffect,useRef,useState} from "react";
import type {OperatorPlan,OperatorPlanningResult} from "./operator-engine";

type Message={id:number;role:"operator"|"assistant";text:string;success?:boolean};

export default function OperatorModal({close,plan,execute,openDownSheet}:{close:()=>void;plan:(command:string)=>OperatorPlanningResult;execute:(plan:OperatorPlan)=>{ok:boolean;message:string};openDownSheet:()=>void}){
 const [command,setCommand]=useState(""),[pending,setPending]=useState<OperatorPlan|null>(null),[messages,setMessages]=useState<Message[]>([{id:1,role:"assistant",text:"Operator ready on this device. I can inspect and locate buses, move them to available areas, record approved defects, and add or complete down-sheet entries. I will preview every change before applying it."}]);
 const endRef=useRef<HTMLDivElement>(null),nextId=useRef(2);
 useEffect(()=>{endRef.current?.scrollIntoView({block:"nearest"})},[messages,pending]);
 const add=(role:Message["role"],text:string,success?:boolean)=>setMessages(current=>[...current,{id:nextId.current++,role,text,success}]);
 const submit=(event:React.FormEvent)=>{event.preventDefault();const value=command.trim();if(!value)return;add("operator",value);setCommand("");const result=plan(value);if(result.kind==="message"){add("assistant",result.message,false);return}if(result.plan.requiresConfirmation){setPending(result.plan);add("assistant","I prepared this change. Review it below and press APPLY CHANGE to continue.");return}const outcome=execute(result.plan);add("assistant",outcome.message,outcome.ok)};
 const apply=()=>{if(!pending)return;const outcome=execute(pending);setPending(null);add("assistant",outcome.message,outcome.ok)};
 const quick=(value:string)=>{setCommand(value);requestAnimationFrame(()=>document.querySelector<HTMLInputElement>(".operator-compose input")?.focus())};
 return <div className="shade operator-shade" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="operator-modal" role="dialog" aria-modal="true" aria-labelledby="operator-title"><header className="operator-head"><span className="operator-mark" aria-hidden="true">✦</span><span><small>PACE INTELLIGENT COMMAND CONSOLE</small><h2 id="operator-title">AI Operator</h2></span><b>DEVICE-LOCAL PILOT</b><button type="button" onClick={close} aria-label="Close AI Operator">×</button></header><div className="operator-boundary"><b>LOCAL SESSION</b><span>This operator can use this device’s tracker and down sheet. It does not synchronize bus arrangements with your other devices yet.</span></div><div className="operator-messages" role="log" aria-live="polite">{messages.map(message=><article className={message.role+(message.success===false?" warning":"")+(message.success===true?" success":"")} key={message.id}><b>{message.role==="operator"?"YOU":"AI OPERATOR"}</b><p>{message.text}</p></article>)}{pending&&<section className="operator-preview"><span><b>CHANGE PREVIEW</b><p>{pending.summary}</p></span><div><button type="button" onClick={()=>{setPending(null);add("assistant","Change canceled. Nothing was updated.")}}>CANCEL</button><button className="operator-apply" type="button" onClick={apply}>APPLY CHANGE</button></div></section>}<div ref={endRef}/></div><div className="operator-quick"><b>TRY A COMMAND</b><div><button type="button" onClick={()=>quick("Locate bus 25")}>Locate bus 25</button><button type="button" onClick={()=>quick("Move bus 25 to CNG East")}>Move a bus</button><button type="button" onClick={()=>quick("Add bus 25 to the down sheet")}>Add to down sheet</button><button type="button" onClick={()=>quick("Add check-engine diagnosis to bus 25")}>Add a defect</button></div></div><form className="operator-compose" onSubmit={submit}><label><span>COMMAND</span><input autoFocus value={command} onChange={event=>setCommand(event.target.value)} placeholder="Example: Move bus 25 to CNG East" disabled={Boolean(pending)}/></label><button type="submit" disabled={!command.trim()||Boolean(pending)}><span aria-hidden="true">✦</span> PREVIEW</button></form><footer className="operator-foot"><span>All changes require confirmation. Full bus numbers are required when two-digit matches are ambiguous.</span><button type="button" onClick={openDownSheet}>OPEN DOWN SHEET</button></footer></section></div>;
}
