"use client";
import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
type S="shop"|"service"|"defect"|"out"|"tow"|"unknown"; type LegacyS=S|"route"; type B={id:string;n:string;s:S;l:string;mechanic:string;foreman:string;shift:string;priority:string;safe:boolean;down:boolean;notes:string;pendingRepair:string;roadcall:boolean;parkedAt:string;outReason:""|"Scheduled"|"Unscheduled"};
const ST:Record<S,[string,string]>={shop:["IN SHOP","#159447"],service:["IN SERVICE / ON ROAD","#1764d8"],defect:["IN SERVICE WITH DEFECTS","#efa400"],out:["OUT OF SERVICE","#c91f27"],tow:["TOW / STAGING","#5e23ad"],unknown:["UNKNOWN / MYSTERY","#777"]};
const DEFAULT_COLORS=Object.fromEntries(Object.entries(ST).map(([key,value])=>[key,value[1]])) as Record<S,string>;
const data:[string,LegacyS,string][]=[["17544","route","service-0"],["17520","shop","service-6"],["17516","service","service-11"],["17534","out","service-16"],["17555","tow","service-23"],["17544","route","paint-0"],["17512","shop","wash-0"],["17509","service","body-0"],["17501","route","bay-1"],["15512","shop","bay-2"],["17526","service","bay-3"],["17500","out","bay-4"],["17518","route","bay-5"],["15520","shop","bay-6"],["17529","route","bay-7"],["17516","shop","bay-8"],["17519","service","bay-9"],["17515","out","bay-10"],["17555","route","bay-11"],["17561","shop","bay-12"],["17531","tow","pit-0"],["17522","route","brake-0"],["17519","tow","tow-0"],["17516","tow","tow-1"],["17508","tow","tow-2"],["17544","route","wall-0"],["17508","shop","wall-5"],["17549","service","wall-10"],["17504","out","wall-14"],["17556","tow","wall-18"],["17533","route","east-0"],["17540","shop","east-1"],["15504","service","east-2"],["17569","out","east-3"],["17570","route","east-4"],["17571","shop","east-5"],["17510","route","garage-0"],["17520","shop","garage-2"],["15516","service","garage-5"],["17534","out","garage-9"],["17561","route","garage-11"],["15508","shop","garage-13"],["17547","route","garage-15"],["17530","shop","garage-18"],["17565","service","garage-24"],["15515","out","garage-26"],["17535","route","garage-31"],["17562","shop","garage-35"],["15516","route","garage-37"],["17549","service","garage-41"],["17550","shop","garage-50"],["17504","out","garage-57"],["17512","route","garage-60"],["17529","service","garage-64"],["17516","shop","garage-68"],["17558","route","garage-71"],["17538","route","west-0"],["18505","shop","west-1"],["17526","service","west-2"],["17539","out","west-3"],["17553","route","west-8"],["17554","shop","west-9"]];
const seed:B[]=data.map((x,i)=>({id:"b"+i,n:x[0],s:x[1]==="route"?"service":x[1]==="service"?"defect":x[1],l:x[2],mechanic:"",foreman:"",shift:"Day",priority:"Normal",safe:x[1]!=="out",down:x[1]==="out",notes:"",pendingRepair:"",roadcall:false,parkedAt:new Date(Date.now()-(i%12)*36e5).toISOString(),outReason:x[1]==="out"?"Unscheduled":""}));
const SINGLE_FILE_CAPACITY=8;
function migrateBuses(source:unknown[],legacy:boolean){
 const now=new Date().toISOString();
 return (source as Partial<B>[]).map(bus=>({...bus,s:(legacy&&bus.s==="service"?"defect":bus.s==="route"?"service":bus.s||"unknown") as S,pendingRepair:bus.pendingRepair??bus.notes??"",roadcall:Boolean(bus.roadcall),parkedAt:bus.parkedAt??now,outReason:bus.outReason??""} as B));
}
function sittingTime(value:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<1)return "Just arrived";if(minutes<60)return minutes+"m";const hours=Math.floor(minutes/60);if(hours<24)return hours+"h "+minutes%60+"m";return Math.floor(hours/24)+"d "+hours%24+"h"}
function migrateSingleFileSlots(source:B[]){
 const migrated=source.map(bus=>({...bus}));
 (["service","wall"] as const).forEach(prefix=>{
  migrated.filter(bus=>bus.l.startsWith(prefix+"-"))
   .sort((a,b)=>(Number(a.l.split("-")[1])||0)-(Number(b.l.split("-")[1])||0))
   .forEach((bus,index)=>{bus.l=index<SINGLE_FILE_CAPACITY?prefix+"-"+index:prefix+"-overflow-"+(index-SINGLE_FILE_CAPACITY)});
 });
 return migrated;
}
function Icon({s}:{s:S}){return <i className="bus" style={{"--c":"var(--status-"+s+")"} as React.CSSProperties}><b/><em/><small/></i>}
function Token({bus,edit}:{bus:B;edit:(b:B)=>void}){const [quick,setQuick]=useState(false),[position,setPosition]=useState({left:0,top:0,below:false}),dragging=useRef(false),anchor=useRef<HTMLButtonElement>(null);const showQuick=()=>{const rect=anchor.current?.getBoundingClientRect();if(!rect)return;const below=rect.top<150,halfWidth=100;setPosition({left:Math.min(window.innerWidth-halfWidth-10,Math.max(halfWidth+10,rect.left+rect.width/2)),top:below?rect.bottom+12:rect.top-12,below});setQuick(true)};const statusLabel=ST[bus.s][0]+(bus.s==="out"&&bus.outReason?" - "+bus.outReason.toUpperCase():"");return <><button ref={anchor} className="token" draggable onMouseEnter={showQuick} onMouseLeave={()=>setQuick(false)} onFocus={showQuick} onBlur={()=>setQuick(false)} onDragStart={e=>{dragging.current=true;setQuick(false);e.dataTransfer.setData("bus",bus.id)}} onDragEnd={()=>{setQuick(false);setTimeout(()=>{dragging.current=false},0)}} onClick={()=>{if(dragging.current)return;setQuick(false);edit(bus)}} aria-label={"Bus "+bus.n+", "+statusLabel}><Icon s={bus.s}/><span className="token-number">{bus.n}</span></button>{quick&&typeof document!=="undefined"&&createPortal(<div className={"quick-view "+(position.below?"below":"above")} style={{left:position.left,top:position.top}} role="tooltip"><span className="quick-bus"><Icon s={bus.s}/><strong>Bus {bus.n}</strong>{bus.roadcall&&<b className="roadcall-badge">ROADCALL</b>}</span><span className="quick-status"><i style={{background:"var(--status-"+bus.s+")"}}/>{statusLabel}</span><span className="quick-sitting"><b>SITTING</b>{sittingTime(bus.parkedAt)}</span>{bus.pendingRepair.trim()&&<span className="quick-detail"><b>PENDING REPAIR</b>{bus.pendingRepair}</span>}</div>,document.body)}</>}
function Spot({id,buses,move,edit}:{id:string;buses:B[];move:(a:string,b:string)=>void;edit:(b:B)=>void}){let b=buses.find(x=>x.l===id);return <div className="spot" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add("ready")}} onDragLeave={e=>e.currentTarget.classList.remove("ready")} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove("ready");move(e.dataTransfer.getData("bus"),id)}}>{b&&<Token bus={b} edit={edit}/>}</div>}
function T({children,menu,count}:{children:React.ReactNode;menu:()=>void;count?:number}){return <div className="title">{children}{count?" ("+count+" SPACES)":""}<button onClick={menu}>...</button></div>}
export default function Home(){const [buses,setBuses]=useState(seed),[edit,setEdit]=useState<B|null>(null),[fold,setFold]=useState(false),[q,setQ]=useState(""),[menu,setMenu]=useState<string|null>(null),[dark,setDark]=useState(false),[hydrated,setHydrated]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[colors,setColors]=useState(DEFAULT_COLORS);
useEffect(()=>{let next=seed;try{let raw=localStorage.getItem("pace-board-v1");if(raw){const saved=JSON.parse(raw);next=Array.isArray(saved)?migrateBuses(saved,true):migrateBuses(saved.buses||[],false)}const ui=JSON.parse(localStorage.getItem("pace-board-settings-v1")||"{}");if(ui.colors)setColors({...DEFAULT_COLORS,...ui.colors});if(typeof ui.dark==="boolean")setDark(ui.dark)}catch{}setBuses(migrateSingleFileSlots(next));setHydrated(true)},[]);useEffect(()=>{if(hydrated){localStorage.setItem("pace-board-v1",JSON.stringify({version:2,buses}));localStorage.setItem("pace-board-settings-v1",JSON.stringify({colors,dark}))}},[buses,colors,dark,hydrated]);useEffect(()=>{Object.entries(colors).forEach(([key,value])=>document.documentElement.style.setProperty("--status-"+key,value))},[colors]);
const show=q?buses.filter(x=>x.n.includes(q)):buses;const move=(id:string,l:string)=>setBuses(v=>!id||v.some(x=>x.l===l&&x.id!==id)?v:v.map(x=>{if(x.id!==id)return x;const nextStatus:S=l.startsWith("bay-")?"shop":l.startsWith("road-")&&x.s==="shop"?"service":x.s;return {...x,l,s:nextStatus,parkedAt:new Date().toISOString()}}));const ttl=(x:string)=><T menu={()=>setMenu(x)}>{x}</T>;const statusStyle=Object.fromEntries(Object.entries(colors).map(([key,value])=>["--status-"+key,value])) as React.CSSProperties;
return <main className={"app "+(dark?"dark":"")} style={statusStyle}><header>PACE MAINTENANCE BUS TRACKING SYSTEM - FACILITY WIDE OVERVIEW</header><nav><div className="legend"><strong>LEGEND:</strong>{Object.entries(ST).map(([k,v])=><span key={k}><Icon s={k as S}/>{v[0]}</span>)}</div><div className="tools"><button className="blue" onClick={()=>setFold(false)}>EXPAND ALL</button><button onClick={()=>setFold(true)}>COLLAPSE ALL</button><button className="green" onClick={()=>scrollTo(0,0)}>FIT TO SCREEN</button><label>Q<input value={q} onChange={e=>setQ(e.target.value.replace(/\D/g,""))} placeholder="Bus #"/></label><button onClick={()=>setSettingsOpen(true)} aria-label="Open settings">GEAR</button></div></nav>
<div className={"facility "+(fold?"fold":"")}><section className="service panel">{ttl("SERVICE DETAIL AREA (SINGLE FILE)")}<div className="single">{Array.from({length:SINGLE_FILE_CAPACITY},(_,i)=><Spot key={i} id={"service-"+i} buses={show} move={move} edit={setEdit}/>)}</div>{show.some(b=>b.l.startsWith("service-overflow-"))&&<div className="overflow"><b>NEEDS REASSIGNMENT</b>{show.filter(b=>b.l.startsWith("service-overflow-")).map(b=><Token key={b.id} bus={b} edit={setEdit}/>)}</div>}</section>
<div className="mid panel"><div className="specials">{([["PAINT BOOTH","paint"],["WASH RACK","wash"],["BODY SHOP","body"]] as const).map(([n,id])=><section className={"special "+id} key={id}>{ttl(n)}<Spot id={id+"-0"} buses={show} move={move} edit={setEdit}/></section>)}</div>
<section className="bays"><T menu={()=>setMenu("SHOP BAYS")}>SHOP BAYS (DIAGONAL - 12 TOTAL)</T><div className="baygrid">{Array.from({length:12},(_,i)=>{const bayNumber=12-i;return <div className="bay" key={bayNumber}><b>{String(bayNumber).padStart(2,"0")}</b><Spot id={"bay-"+bayNumber} buses={show} move={move} edit={setEdit}/></div>})}</div></section>
<div className="vertical">{([["PIT","pit",1],["BRAKE TEST","brake",1],["TOW STAGING","tow",3]] as const).map(([n,id,c])=><section key={id}>{ttl(n)}<div className="vspots">{Array.from({length:c},(_,i)=><Spot key={i} id={id+"-"+i} buses={show} move={move} edit={setEdit}/>)}</div></section>)}</div>
<section className="east lot"><T count={28} menu={()=>setMenu("CNG EAST LOT")}>CNG EAST LOT</T><div className="lotgrid eastgrid">{Array.from({length:28},(_,i)=><Spot key={i} id={"east-"+i} buses={show} move={move} edit={setEdit}/>)}</div><p>TOTAL SPACES: 28</p></section><section className="road">{ttl("IN SERVICE / ON ROAD")}<div className="roadgrid">{Array.from({length:8},(_,i)=><Spot key={i} id={"road-"+i} buses={show} move={move} edit={setEdit}/>)}</div><p>UNLISTED BUSES ARE ASSUMED ON ROAD</p></section><section className="wall">{ttl("SHOP WALL (SINGLE FILE)")}<div className="single">{Array.from({length:SINGLE_FILE_CAPACITY},(_,i)=><Spot key={i} id={"wall-"+i} buses={show} move={move} edit={setEdit}/>)}</div>{show.some(b=>b.l.startsWith("wall-overflow-"))&&<div className="overflow"><b>NEEDS REASSIGNMENT</b>{show.filter(b=>b.l.startsWith("wall-overflow-")).map(b=><Token key={b.id} bus={b} edit={setEdit}/>)}</div>}</section></div>
<div className="bottom"><section className="garage panel">{ttl("MAIN GARAGE (BAYS 1-12)")}<div className="garagegrid"><i/>{Array.from({length:12},(_,i)=><b key={i}>{String(i+1).padStart(2,"0")}</b>)}{Array.from({length:7},(_,r)=><div className="grow" key={r}><strong>ROW {r+1}</strong>{Array.from({length:12},(_,c)=><Spot key={c} id={"garage-"+(r*12+c)} buses={show} move={move} edit={setEdit}/>)}</div>)}</div></section><section className="west lot panel"><T count={40} menu={()=>setMenu("CNG WEST LOT")}>CNG WEST LOT</T><div className="lotgrid westgrid">{Array.from({length:40},(_,i)=><Spot key={i} id={"west-"+i} buses={show} move={move} edit={setEdit}/>)}</div><p>TOTAL SPACES: 40</p></section></div></div>
<footer>i &nbsp; DRAG BUSES TO MOVE THEM &nbsp; - &nbsp; CLICK A BUS TO EDIT DETAILS &nbsp; - &nbsp; EMPTY SPACES ARE READY FOR ASSIGNMENT</footer>{menu&&<aside><b>{menu}</b><button onClick={()=>setMenu(null)}>X</button><p>Section controls are ready for the next build phase.</p><div><button>ADD BUS</button><button>EDIT SECTION</button></div></aside>}{edit&&<Editor b={edit} close={()=>setEdit(null)} save={x=>{setBuses(v=>v.map(y=>y.id===x.id?x:y));setEdit(null)}} remove={id=>{setBuses(v=>v.filter(x=>x.id!==id));setEdit(null)}}/>}{settingsOpen&&<StatusSettings colors={colors} setColors={setColors} dark={dark} setDark={setDark} close={()=>setSettingsOpen(false)}/>}</main>}
function Editor({b,close,save,remove}:{b:B;close:()=>void;save:(x:B)=>void;remove:(x:string)=>void}){const [d,setD]=useState(b),f=(k:keyof B,v:unknown)=>setD(x=>({...x,[k]:v}));return <div className="shade"><form className="modal" onSubmit={e=>{e.preventDefault();save(d)}}><div className="mhead"><span>FLEET UNIT<h2>Bus {d.n}</h2></span><button type="button" onClick={close}>X</button></div><div className="form"><label>BUS NUMBER<input value={d.n} onChange={e=>f("n",e.target.value)}/></label><label>STATUS<select value={d.s} onChange={e=>f("s",e.target.value)}>{Object.entries(ST).map(([k,v])=><option value={k} key={k}>{v[0]}</option>)}</select></label><label>ASSIGNED MECHANIC<input value={d.mechanic} onChange={e=>f("mechanic",e.target.value)}/></label><label>FOREMAN<input value={d.foreman} onChange={e=>f("foreman",e.target.value)}/></label><label>SHIFT<select value={d.shift} onChange={e=>f("shift",e.target.value)}><option>Day</option><option>Evening</option><option>Night</option></select></label><label>PRIORITY<select value={d.priority} onChange={e=>f("priority",e.target.value)}><option>Low</option><option>Normal</option><option>High</option><option>Critical</option></select></label><label className="check"><input type="checkbox" checked={d.roadcall} onChange={e=>f("roadcall",e.target.checked)}/> ROADCALL</label><label className="check"><input type="checkbox" checked={d.down} onChange={e=>f("down",e.target.checked)}/> ON DOWNSHEET</label>{d.s==="out"&&<label>OUT-OF-SERVICE TYPE<select value={d.outReason} onChange={e=>f("outReason",e.target.value)}><option value="">Not specified</option><option>Scheduled</option><option>Unscheduled</option></select></label>}<label className="wide">PENDING REPAIR<textarea value={d.pendingRepair} onChange={e=>f("pendingRepair",e.target.value)} placeholder="Shown in the hover snapshot when present"/></label><label className="wide">REPAIR NOTES / HISTORY<textarea value={d.notes} onChange={e=>f("notes",e.target.value)}/></label></div><div className="actions"><button type="button" className="delete" onClick={()=>remove(b.id)}>DELETE BUS</button><span/><button type="button" onClick={close}>CANCEL</button><button className="save">SAVE CHANGES</button></div></form></div>}
function StatusSettings({colors,setColors,dark,setDark,close}:{colors:Record<S,string>;setColors:React.Dispatch<React.SetStateAction<Record<S,string>>>;dark:boolean;setDark:(value:boolean)=>void;close:()=>void}){return <div className="shade settings-shade" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="settings-modal"><div className="mhead"><span>DISPLAY SETTINGS<h2>Status Colors</h2></span><button onClick={close}>X</button></div><div className="color-settings">{(Object.keys(ST) as S[]).map(status=><label key={status}><span><Icon s={status}/>{ST[status][0]}</span><input type="color" value={colors[status]} onChange={e=>setColors(current=>({...current,[status]:e.target.value}))}/></label>)}<label className="theme-setting"><span>DARK THEME</span><input type="checkbox" checked={dark} onChange={e=>setDark(e.target.checked)}/></label></div><div className="settings-actions"><button onClick={()=>setColors(DEFAULT_COLORS)}>RESET COLORS</button><button className="save" onClick={close}>DONE</button></div></section></div>}