"use client";
import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
type S="shop"|"service"|"defect"|"out"|"decommissioned"|"unknown"; type LegacyS=S|"route"|"tow"; type B={id:string;n:string;s:S;l:string;mechanic:string;foreman:string;shift:string;priority:string;safe:boolean;down:boolean;notes:string;pendingRepair:string;roadcall:boolean;parkedAt:string;outReason:""|"Scheduled"|"Unscheduled"};
const ST:Record<S,[string,string]>={service:["IN SERVICE / ON ROAD","#1764d8"],defect:["IN SERVICE WITH DEFECTS","#159447"],shop:["WORK IN PROGRESS","#efa400"],out:["OUT OF SERVICE","#c91f27"],decommissioned:["DECOMMISSIONED / DOWN INDEFINITELY","#343a40"],unknown:["UNKNOWN / MYSTERY","#777"]};
const DEFAULT_COLORS=Object.fromEntries(Object.entries(ST).map(([key,value])=>[key,value[1]])) as Record<S,string>;
const SECTION_THEME_KEYS=[["service","Service Detail"],["paint","Paint Booth"],["wash","Wash Rack"],["body","Body Shop"],["bays","Shop Bays"],["pit","Pit"],["brake","Brake Test"],["tow","Tow Staging"],["east","CNG East"],["road","In Service / On Road"],["wall","Shop Wall"],["garage","Main Garage"],["west","CNG West"]] as const;
type SectionThemeKey=typeof SECTION_THEME_KEYS[number][0];
type Visuals={page:string;panel:string;text:string;header:string;headerText:string;title:string;border:string;slot:string;command:string;commandText:string;sections:Record<SectionThemeKey,string>};
const sectionFill=(color:string)=>Object.fromEntries(SECTION_THEME_KEYS.map(([key])=>[key,color])) as Record<SectionThemeKey,string>;
const DEFAULT_VISUALS:Visuals={page:"#f4f6fa",panel:"#ffffff",text:"#112657",header:"#06275c",headerText:"#ffffff",title:"#172957",border:"#9cadd1",slot:"#ffffff",command:"#16284d",commandText:"#ffffff",sections:sectionFill("#fbfcff")};
const THEMES:Record<string,{label:string;visuals:Visuals;colors:Record<S,string>}>= {
 default:{label:"Default",visuals:DEFAULT_VISUALS,colors:DEFAULT_COLORS},
 terminal:{label:"Terminal",visuals:{page:"#021b10",panel:"#052719",text:"#b8ffd3",header:"#00150c",headerText:"#61ff9d",title:"#61ff9d",border:"#197444",slot:"#0a3322",command:"#00150c",commandText:"#61ff9d",sections:sectionFill("#062d1d")},colors:{service:"#20a4ff",defect:"#00ff75",shop:"#ffe600",out:"#ff4050",decommissioned:"#343a40",unknown:"#8bbca0"}},
 black:{label:"Black / Dark",visuals:{page:"#000000",panel:"#111111",text:"#f1f1f1",header:"#000000",headerText:"#ffffff",title:"#ffffff",border:"#444444",slot:"#181818",command:"#050505",commandText:"#ffffff",sections:sectionFill("#111111")},colors:{service:"#3b82f6",defect:"#25c466",shop:"#f4b400",out:"#ef3340",decommissioned:"#2b2b2b",unknown:"#8a8a8a"}},
 midnight:{label:"Midnight",visuals:{page:"#071225",panel:"#0d1d38",text:"#dbe9ff",header:"#020a18",headerText:"#ffffff",title:"#79a9ff",border:"#27446e",slot:"#132847",command:"#030c1c",commandText:"#dbe9ff",sections:sectionFill("#0f213f")},colors:{service:"#3388ff",defect:"#27c978",shop:"#ffc928",out:"#ff4d5e",decommissioned:"#273142",unknown:"#8496b2"}},
 tactical:{label:"Tactical",visuals:{page:"#25281e",panel:"#34392a",text:"#e5e2c6",header:"#15180f",headerText:"#e7ddb2",title:"#d2c38f",border:"#697056",slot:"#414733",command:"#171a12",commandText:"#e7ddb2",sections:sectionFill("#383e2e")},colors:{service:"#4f87b8",defect:"#6fae4f",shop:"#d4aa3e",out:"#b94b43",decommissioned:"#2a2d27",unknown:"#8b8e78"}}
};
const data:[string,LegacyS,string][]=[["17544","route","service-0"],["17520","shop","service-6"],["17516","service","service-11"],["17534","out","service-16"],["17555","tow","service-23"],["17544","route","paint-0"],["17512","shop","wash-0"],["17509","service","body-0"],["17501","route","bay-1"],["15512","shop","bay-2"],["17526","service","bay-3"],["17500","out","bay-4"],["17518","route","bay-5"],["15520","shop","bay-6"],["17529","route","bay-7"],["17516","shop","bay-8"],["17519","service","bay-9"],["17515","out","bay-10"],["17555","route","bay-11"],["17561","shop","bay-12"],["17531","tow","pit-0"],["17522","route","brake-0"],["17519","tow","tow-0"],["17516","tow","tow-1"],["17508","tow","tow-2"],["17544","route","wall-0"],["17508","shop","wall-5"],["17549","service","wall-10"],["17504","out","wall-14"],["17556","tow","wall-18"],["17533","route","east-0"],["17540","shop","east-1"],["15504","service","east-2"],["17569","out","east-3"],["17570","route","east-4"],["17571","shop","east-5"],["17510","route","garage-0"],["17520","shop","garage-2"],["15516","service","garage-5"],["17534","out","garage-9"],["17561","route","garage-11"],["15508","shop","garage-13"],["17547","route","garage-15"],["17530","shop","garage-18"],["17565","service","garage-24"],["15515","out","garage-26"],["17535","route","garage-31"],["17562","shop","garage-35"],["15516","route","garage-37"],["17549","service","garage-41"],["17550","shop","garage-50"],["17504","out","garage-57"],["17512","route","garage-60"],["17529","service","garage-64"],["17516","shop","garage-68"],["17558","route","garage-71"],["17538","route","west-0"],["18505","shop","west-1"],["17526","service","west-2"],["17539","out","west-3"],["17553","route","west-8"],["17554","shop","west-9"]];
const seed:B[]=data.map((x,i)=>{const status:S=x[1]==="route"?"service":x[1]==="service"?"defect":x[1]==="tow"?"out":x[1];const unavailable=status==="out"||status==="decommissioned";return {id:"b"+i,n:x[0],s:status,l:x[2],mechanic:"",foreman:"",shift:"Day",priority:"Normal",safe:!unavailable,down:unavailable,notes:"",pendingRepair:"",roadcall:false,parkedAt:new Date(Date.now()-(i%12)*36e5).toISOString(),outReason:status==="out"?"Unscheduled":""}});
const SINGLE_FILE_CAPACITY=8;
const slots=(prefix:string,count:number,start=0)=>Array.from({length:count},(_,index)=>prefix+"-"+(index+start));
const SECTION_SLOTS:Record<string,string[]>={
 "SERVICE DETAIL AREA (SINGLE FILE)":slots("service",8),
 "PAINT BOOTH":slots("paint",1),
 "WASH RACK":slots("wash",1),
 "BODY SHOP":slots("body",1),
 "SHOP BAYS (DIAGONAL)":slots("bay",12,1),
 "PIT":slots("pit",1),
 "BRAKE TEST":slots("brake",1),
 "TOW STAGING":slots("tow",3),
 "CNG EAST LOT":slots("east",28),
 "IN SERVICE / ON ROAD":slots("road",32),
 "SHOP WALL (SINGLE FILE)":slots("wall",8),
 "MAIN GARAGE (BAYS 1-12)":slots("garage",84),
 "CNG WEST LOT":slots("west",40)
};
function migrateBuses(source:unknown[],legacy:boolean){
 const now=new Date().toISOString();
 return (source as (Partial<Omit<B,"s">>&{s?:LegacyS})[]).map(bus=>{const original=bus.s;const status:S=legacy&&original==="service"?"defect":original==="route"?"service":original==="tow"?"out":original||"unknown";const unavailable=status==="out"||status==="decommissioned";return {...bus,s:status,pendingRepair:bus.pendingRepair??bus.notes??"",roadcall:Boolean(bus.roadcall),parkedAt:bus.parkedAt??now,safe:original==="tow"?false:bus.safe??!unavailable,down:original==="tow"?true:bus.down??unavailable,outReason:bus.outReason??(original==="tow"?"Unscheduled":"")} as B});
}
function sittingTime(value:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<1)return "Just arrived";if(minutes<60)return minutes+"m";const hours=Math.floor(minutes/60);if(hours<24)return hours+"h "+minutes%60+"m";return Math.floor(hours/24)+"d "+hours%24+"h"}
function migrateSingleFileSlots(source:B[]){
 const migrated=source.map(bus=>({...bus}));
 (["service","wall"] as const).forEach(prefix=>{
  migrated.filter(bus=>bus.l.startsWith(prefix+"-"))
   .sort((a,b)=>(Number(a.l.split("-")[1])||0)-(Number(b.l.split("-")[1])||0))
   .forEach((bus,index)=>{bus.l=index<SINGLE_FILE_CAPACITY?prefix+"-"+index:prefix+"-overflow-"+(index-SINGLE_FILE_CAPACITY)});
 });
 return migrated;
}
function Icon({s}:{s:S}){return <i className="bus" style={{"--c":"var(--status-"+s+")"} as React.CSSProperties}><b/><em/><small/></i>}
function Token({bus,edit}:{bus:B;edit:(b:B)=>void}){const [quick,setQuick]=useState(false),[position,setPosition]=useState({left:0,top:0,below:false}),dragging=useRef(false),anchor=useRef<HTMLButtonElement>(null),lastTouch=useRef(0),suppressClick=useRef(0),pointerType=useRef("");const showQuick=()=>{const rect=anchor.current?.getBoundingClientRect();if(!rect)return;const below=rect.top<150,halfWidth=100;setPosition({left:Math.min(window.innerWidth-halfWidth-10,Math.max(halfWidth+10,rect.left+rect.width/2)),top:below?rect.bottom+12:rect.top-12,below});setQuick(true)};useEffect(()=>{if(!quick)return;const dismiss=(event:PointerEvent)=>{if(event.pointerType==="touch"&&!anchor.current?.contains(event.target as Node))setQuick(false)};document.addEventListener("pointerdown",dismiss);return()=>document.removeEventListener("pointerdown",dismiss)},[quick]);const statusLabel=ST[bus.s][0]+(bus.s==="out"&&bus.outReason?" - "+bus.outReason.toUpperCase():"");return <><button ref={anchor} className="token" data-bus-id={bus.id} data-status={bus.s} data-pending={Boolean(bus.pendingRepair.trim())} draggable onPointerDown={e=>{pointerType.current=e.pointerType}} onPointerUp={e=>{if(e.pointerType!=="touch")return;const now=Date.now();suppressClick.current=now+500;if(now-lastTouch.current<350){lastTouch.current=0;setQuick(false);edit(bus)}else{lastTouch.current=now;showQuick()}}} onMouseEnter={()=>{if(Date.now()<suppressClick.current)return;pointerType.current="mouse";showQuick()}} onMouseLeave={()=>{if(pointerType.current!=="touch")setQuick(false)}} onFocus={showQuick} onBlur={()=>{if(pointerType.current!=="touch")setQuick(false)}} onDragStart={e=>{dragging.current=true;setQuick(false);e.dataTransfer.setData("bus",bus.id)}} onDragEnd={()=>{setQuick(false);setTimeout(()=>{dragging.current=false},0)}} onClick={()=>{if(dragging.current||Date.now()<suppressClick.current)return;setQuick(false);edit(bus)}} aria-label={"Bus "+bus.n+", "+statusLabel}><Icon s={bus.s}/><span className="token-number">{bus.n}</span></button>{quick&&typeof document!=="undefined"&&createPortal(<div className={"quick-view "+(position.below?"below":"above")} style={{left:position.left,top:position.top}} role="tooltip"><span className="quick-bus"><Icon s={bus.s}/><strong>Bus {bus.n}</strong>{bus.roadcall&&<b className="roadcall-badge">ROADCALL</b>}</span><span className="quick-status"><i style={{background:"var(--status-"+bus.s+")"}}/>{statusLabel}</span><span className="quick-sitting"><b>SITTING</b>{sittingTime(bus.parkedAt)}</span>{bus.pendingRepair.trim()&&<span className="quick-detail"><b>PENDING REPAIR</b>{bus.pendingRepair}</span>}</div>,document.body)}</>}
function Spot({id,buses,move,edit}:{id:string;buses:B[];move:(a:string,b:string)=>void;edit:(b:B)=>void}){const b=buses.find(x=>x.l===id);return <div className="spot" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add("ready")}} onDragLeave={e=>e.currentTarget.classList.remove("ready")} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove("ready");move(e.dataTransfer.getData("bus"),id)}}>{b&&<Token bus={b} edit={edit}/>}</div>}
function T({children,menu,onAdd,onRemove}:{children:React.ReactNode;menu:()=>void;count?:number;onAdd?:()=>void;onRemove?:()=>void}){return <div className="title"><span>{children}</span><span className="title-actions">{onAdd&&<button className="add-space" onClick={onAdd} aria-label="Add bus to section">+</button>}{onRemove&&<button className="remove-space" onClick={onRemove} aria-label="Remove bus from section">-</button>}<button className="more-section" onClick={menu} aria-label="Section settings">...</button></span></div>}
export default function Home(){const [buses,setBuses]=useState(seed),[edit,setEdit]=useState<B|null>(null),[fold,setFold]=useState(false),[q,setQ]=useState(""),[menu,setMenu]=useState<string|null>(null),[hydrated,setHydrated]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[colors,setColors]=useState(DEFAULT_COLORS),[visuals,setVisuals]=useState(DEFAULT_VISUALS),[themeName,setThemeName]=useState("default"),[highlight,setHighlight]=useState<"all"|"service"|"pending"|null>(null),[locateNumber,setLocateNumber]=useState(""),[draftNewId,setDraftNewId]=useState<string|null>(null),[removeSection,setRemoveSection]=useState<string|null>(null);
// Stored fleet state is intentionally restored once after client hydration.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{let next=seed;try{const raw=localStorage.getItem("pace-board-v1");if(raw){const saved=JSON.parse(raw);next=Array.isArray(saved)?migrateBuses(saved,true):migrateBuses(saved.buses||[],false)}const ui=JSON.parse(localStorage.getItem("pace-board-settings-v1")||"{}");const savedTheme=typeof ui.theme==="string"?ui.theme:ui.dark?"black":"default";if(ui.statusVersion===3&&ui.colors)setColors({...DEFAULT_COLORS,...ui.colors});else setColors({...((THEMES[savedTheme]||THEMES.default).colors)});if(ui.visuals)setVisuals({...DEFAULT_VISUALS,...ui.visuals,sections:{...DEFAULT_VISUALS.sections,...ui.visuals.sections}});if(ui.theme)setThemeName(ui.theme);else if(ui.dark){setVisuals(THEMES.black.visuals);setThemeName("black")}}catch{}setBuses(migrateSingleFileSlots(next));setHydrated(true)},[]);
useEffect(()=>{if(hydrated){localStorage.setItem("pace-board-v1",JSON.stringify({version:3,buses}));localStorage.setItem("pace-board-settings-v1",JSON.stringify({statusVersion:3,colors,visuals,theme:themeName}))}},[buses,colors,visuals,themeName,hydrated]);
useEffect(()=>{const root=document.documentElement;Object.entries(colors).forEach(([key,value])=>root.style.setProperty("--status-"+key,value));root.style.setProperty("--page-bg",visuals.page);root.style.setProperty("--panel-bg",visuals.panel);root.style.setProperty("--theme-text",visuals.text);root.style.setProperty("--header-bg",visuals.header);root.style.setProperty("--header-text",visuals.headerText);root.style.setProperty("--title-color",visuals.title);root.style.setProperty("--theme-border",visuals.border);root.style.setProperty("--slot-bg",visuals.slot);root.style.setProperty("--command-bg",visuals.command);root.style.setProperty("--command-text",visuals.commandText);Object.entries(visuals.sections).forEach(([key,value])=>root.style.setProperty("--section-"+key,value))},[colors,visuals]);
const show=q?buses.filter(x=>x.n.includes(q)):buses;
const move=(id:string,l:string)=>setBuses(v=>!id||v.some(x=>x.l===l&&x.id!==id)?v:v.map(x=>{if(x.id!==id)return x;const nextStatus:S=l.startsWith("bay-")?"shop":l.startsWith("road-")&&x.s==="shop"?"service":x.s;return {...x,l,s:nextStatus,parkedAt:new Date().toISOString()}}));
// IDs and timestamps are created only in response to the Add command.
// eslint-disable-next-line react-hooks/purity
const addBus=(section:string)=>{const location=SECTION_SLOTS[section]?.find(slot=>!buses.some(bus=>bus.l===slot));if(!location){alert(section+" has no empty spaces.");return}const id="bus-"+Date.now(),bus:B={id,n:"",s:location.startsWith("bay-")?"shop":"service",l:location,mechanic:"",foreman:"",shift:"Day",priority:"Normal",safe:true,down:false,notes:"",pendingRepair:"",roadcall:false,parkedAt:new Date().toISOString(),outReason:""};setBuses(current=>[...current,bus]);setDraftNewId(id);setEdit(bus)};
const ttl=(x:string,count?:number)=><T count={count} menu={()=>setMenu(x)} onAdd={()=>addBus(x)} onRemove={()=>setRemoveSection(x)}>{x}</T>;
const applyTheme=(name:string)=>{const preset=THEMES[name];if(!preset)return;setThemeName(name);setVisuals({...preset.visuals,sections:{...preset.visuals.sections}});setColors({...preset.colors})};
const locateBus=(event:React.FormEvent)=>{event.preventDefault();const needle=locateNumber.trim();if(!needle)return;const bus=buses.find(item=>item.n===needle);if(!bus){alert("Bus "+needle+" is not currently placed on this map.");return}const token=document.querySelector<HTMLElement>('[data-bus-id="'+bus.id+'"]');const target=token?.closest<HTMLElement>(".spot")||token;if(!target)return;target.scrollIntoView({behavior:"smooth",block:"center",inline:"center"});target.classList.remove("locate-pulse");void target.offsetWidth;target.classList.add("locate-pulse");window.setTimeout(()=>target.classList.remove("locate-pulse"),5200)};
const themeStyle=Object.fromEntries([...Object.entries(colors).map(([key,value])=>["--status-"+key,value]),["--page-bg",visuals.page],["--panel-bg",visuals.panel],["--theme-text",visuals.text],["--header-bg",visuals.header],["--header-text",visuals.headerText],["--title-color",visuals.title],["--theme-border",visuals.border],["--slot-bg",visuals.slot],["--command-bg",visuals.command],["--command-text",visuals.commandText],...Object.entries(visuals.sections).map(([key,value])=>["--section-"+key,value])]) as React.CSSProperties;return <main className={"app "+(highlight?"highlight-"+highlight:"")} style={themeStyle}><header>PACE MAINTENANCE BUS TRACKING SYSTEM - FACILITY WIDE OVERVIEW</header><nav><div className="legend"><strong>LEGEND:</strong>{Object.entries(ST).map(([k,v])=><span key={k}><Icon s={k as S}/>{v[0]}</span>)}</div><div className="tools"><button className="blue" onClick={()=>setFold(false)}>EXPAND ALL</button><button onClick={()=>setFold(true)}>COLLAPSE ALL</button><button className="green" onClick={()=>scrollTo(0,0)}>FIT TO SCREEN</button><label>Q<input value={q} onChange={e=>setQ(e.target.value.replace(/\D/g,""))} placeholder="Bus #"/></label></div></nav>
<div className={"facility "+(fold?"fold":"")}><section className="service panel">{ttl("SERVICE DETAIL AREA (SINGLE FILE)")}<div className="single">{Array.from({length:SINGLE_FILE_CAPACITY},(_,i)=><Spot key={i} id={"service-"+i} buses={show} move={move} edit={setEdit}/>)}</div>{show.some(b=>b.l.startsWith("service-overflow-"))&&<div className="overflow"><b>NEEDS REASSIGNMENT</b>{show.filter(b=>b.l.startsWith("service-overflow-")).map(b=><Token key={b.id} bus={b} edit={setEdit}/>)}</div>}</section>
<div className="mid panel"><div className="specials">{([["PAINT BOOTH","paint"],["WASH RACK","wash"],["BODY SHOP","body"]] as const).map(([n,id])=><section className={"special "+id} key={id}>{ttl(n)}<Spot id={id+"-0"} buses={show} move={move} edit={setEdit}/></section>)}</div>
<section className="bays">{ttl("SHOP BAYS (DIAGONAL)")}<div className="baygrid">{Array.from({length:12},(_,i)=>{const bayNumber=12-i;return <div className="bay" key={bayNumber}><b>{String(bayNumber).padStart(2,"0")}</b><Spot id={"bay-"+bayNumber} buses={show} move={move} edit={setEdit}/></div>})}</div></section>
<div className="vertical">{([["PIT","pit",1],["BRAKE TEST","brake",1],["TOW STAGING","tow",3]] as const).map(([n,id,c])=><section className={"vertical-zone "+id} key={id}>{ttl(n)}<div className="vspots">{Array.from({length:c},(_,i)=><Spot key={i} id={id+"-"+i} buses={show} move={move} edit={setEdit}/>)}</div></section>)}</div>
<section className="east lot">{ttl("CNG EAST LOT")}<div className="lotgrid eastgrid">{Array.from({length:28},(_,i)=><Spot key={i} id={"east-"+i} buses={show} move={move} edit={setEdit}/>)}</div></section><section className="road">{ttl("IN SERVICE / ON ROAD")}<div className="roadgrid">{Array.from({length:32},(_,i)=><Spot key={i} id={"road-"+i} buses={show} move={move} edit={setEdit}/>)}</div><p>UNLISTED BUSES ARE ASSUMED ON ROAD</p></section><section className="wall">{ttl("SHOP WALL (SINGLE FILE)")}<div className="single">{Array.from({length:SINGLE_FILE_CAPACITY},(_,i)=><Spot key={i} id={"wall-"+i} buses={show} move={move} edit={setEdit}/>)}</div>{show.some(b=>b.l.startsWith("wall-overflow-"))&&<div className="overflow"><b>NEEDS REASSIGNMENT</b>{show.filter(b=>b.l.startsWith("wall-overflow-")).map(b=><Token key={b.id} bus={b} edit={setEdit}/>)}</div>}</section></div>
<div className="bottom"><section className="garage panel">{ttl("MAIN GARAGE (BAYS 1-12)")}<div className="garagegrid"><i/>{Array.from({length:12},(_,i)=><b key={i}>{String(i+1).padStart(2,"0")}</b>)}{Array.from({length:7},(_,r)=><div className="grow" key={r}><strong>ROW {r+1}</strong>{Array.from({length:12},(_,c)=><Spot key={c} id={"garage-"+(r*12+c)} buses={show} move={move} edit={setEdit}/>)}</div>)}</div></section><section className="west lot panel">{ttl("CNG WEST LOT")}<div className="lotgrid westgrid">{Array.from({length:40},(_,i)=><Spot key={i} id={"west-"+i} buses={show} move={move} edit={setEdit}/>)}</div></section></div></div>
<footer className="command-bar"><div className="command-highlights"><button className={highlight==="all"?"active":""} onClick={()=>setHighlight(value=>value==="all"?null:"all")}>ALL BUSES</button><button className={highlight==="service"?"active":""} onClick={()=>setHighlight(value=>value==="service"?null:"service")}>IN SERVICE</button><button className={highlight==="pending"?"active":""} onClick={()=>setHighlight(value=>value==="pending"?null:"pending")}>PENDING REPAIR</button></div><form className="locate-command" onSubmit={locateBus}><input inputMode="numeric" value={locateNumber} onChange={event=>setLocateNumber(event.target.value.replace(/\D/g,""))} placeholder="Bus #" aria-label="Bus number to locate"/><button>LOCATE</button></form><button className="settings-command" onClick={()=>setSettingsOpen(true)} aria-label="Open appearance settings"><span aria-hidden="true">⚙</span> SETTINGS</button></footer>{menu&&<aside><b>{menu}</b><button onClick={()=>setMenu(null)}>X</button><p>Section controls are ready for the next build phase.</p><div><button>ADD BUS</button><button>EDIT SECTION</button></div></aside>}{edit&&<Editor b={edit} close={()=>{if(draftNewId===edit.id)setBuses(v=>v.filter(bus=>bus.id!==edit.id));setDraftNewId(null);setEdit(null)}} save={x=>{setBuses(v=>v.map(y=>y.id===x.id?x:y));setDraftNewId(null);setEdit(null)}} remove={id=>{setBuses(v=>v.filter(x=>x.id!==id));setDraftNewId(null);setEdit(null)}}/>}{removeSection&&<RemoveBusPicker name={removeSection} buses={buses.filter(bus=>SECTION_SLOTS[removeSection]?.includes(bus.l))} close={()=>setRemoveSection(null)} remove={id=>setBuses(current=>current.filter(bus=>bus.id!==id))}/>}{settingsOpen&&<StatusSettings colors={colors} setColors={setColors} visuals={visuals} setVisuals={setVisuals} themeName={themeName} setThemeName={setThemeName} applyTheme={applyTheme} close={()=>setSettingsOpen(false)}/>}</main>}
function Editor({b,close,save,remove}:{b:B;close:()=>void;save:(x:B)=>void;remove:(x:string)=>void}){const [d,setD]=useState(b),f=(k:keyof B,v:unknown)=>setD(x=>({...x,[k]:v}));return <div className="shade"><form className="modal" onSubmit={e=>{e.preventDefault();save(d)}}><div className="mhead"><span>FLEET UNIT<h2>Bus {d.n}</h2></span><button type="button" onClick={close}>X</button></div><div className="form"><label>BUS NUMBER<input required value={d.n} onChange={e=>f("n",e.target.value)}/></label><label>STATUS<select value={d.s} onChange={e=>f("s",e.target.value)}>{Object.entries(ST).map(([k,v])=><option value={k} key={k}>{v[0]}</option>)}</select></label><label>ASSIGNED MECHANIC<input value={d.mechanic} onChange={e=>f("mechanic",e.target.value)}/></label><label>FOREMAN<input value={d.foreman} onChange={e=>f("foreman",e.target.value)}/></label><label>SHIFT<select value={d.shift} onChange={e=>f("shift",e.target.value)}><option>Day</option><option>Evening</option><option>Night</option></select></label><label>PRIORITY<select value={d.priority} onChange={e=>f("priority",e.target.value)}><option>Low</option><option>Normal</option><option>High</option><option>Critical</option></select></label><label className="check"><input type="checkbox" checked={d.roadcall} onChange={e=>f("roadcall",e.target.checked)}/> ROADCALL</label><label className="check"><input type="checkbox" checked={d.down} onChange={e=>f("down",e.target.checked)}/> ON DOWNSHEET</label>{d.s==="out"&&<label>OUT-OF-SERVICE TYPE<select value={d.outReason} onChange={e=>f("outReason",e.target.value)}><option value="">Not specified</option><option>Scheduled</option><option>Unscheduled</option></select></label>}<label className="wide">PENDING REPAIR<textarea value={d.pendingRepair} onChange={e=>f("pendingRepair",e.target.value)} placeholder="Shown in the hover snapshot when present"/></label><label className="wide">REPAIR NOTES / HISTORY<textarea value={d.notes} onChange={e=>f("notes",e.target.value)}/></label></div><div className="actions"><button type="button" className="delete" onClick={()=>remove(b.id)}>DELETE BUS</button><span/><button type="button" onClick={close}>CANCEL</button><button className="save">SAVE CHANGES</button></div></form></div>}
function ColorField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="color-field"><span>{label}</span><input type="color" value={value} onChange={event=>onChange(event.target.value)}/><code>{value.toUpperCase()}</code></label>}
function StatusSettings({colors,setColors,visuals,setVisuals,themeName,setThemeName,applyTheme,close}:{colors:Record<S,string>;setColors:React.Dispatch<React.SetStateAction<Record<S,string>>>;visuals:Visuals;setVisuals:React.Dispatch<React.SetStateAction<Visuals>>;themeName:string;setThemeName:(value:string)=>void;applyTheme:(name:string)=>void;close:()=>void}){
 const manualVisual=(key:Exclude<keyof Visuals,"sections">,value:string)=>{setThemeName("custom");setVisuals(current=>({...current,[key]:value}))};
 const manualSection=(key:SectionThemeKey,value:string)=>{setThemeName("custom");setVisuals(current=>({...current,sections:{...current.sections,[key]:value}}))};
 const manualStatus=(status:S,value:string)=>{setThemeName("custom");setColors(current=>({...current,[status]:value}))};
 const globalFields=[["page","Page Background"],["panel","Panel Background"],["text","Main Text"],["header","Header Background"],["headerText","Header Text"],["title","Section Title Text"],["border","Borders / Lines"],["slot","Parking Spaces"],["command","Command Bar"],["commandText","Command Text"]] as const;
 return <div className="shade settings-shade" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="settings-modal"><div className="mhead"><span>DISPLAY SETTINGS<h2>Dashboard Appearance</h2></span><button onClick={close}>X</button></div><div className="settings-body"><section className="settings-group"><h3>THEMES</h3><p>Apply a complete dashboard and bus-color preset. You can fine-tune anything below.</p><div className="theme-grid">{Object.entries(THEMES).map(([key,preset])=><button className={themeName===key?"active":""} key={key} onClick={()=>applyTheme(key)}><i style={{background:preset.visuals.page,borderColor:preset.visuals.border}}/><b>{preset.label}</b></button>)}</div>{themeName==="custom"&&<div className="custom-theme-badge">CUSTOM MANUAL COLORS</div>}</section><section className="settings-group"><h3>MANUAL DASHBOARD COLORS</h3><div className="manual-grid">{globalFields.map(([key,label])=><ColorField key={key} label={label} value={visuals[key]} onChange={value=>manualVisual(key,value)}/>)}</div></section><section className="settings-group"><h3>SECTION BACKGROUNDS</h3><div className="manual-grid section-color-grid">{SECTION_THEME_KEYS.map(([key,label])=><ColorField key={key} label={label} value={visuals.sections[key]} onChange={value=>manualSection(key,value)}/>)}</div></section><section className="settings-group"><h3>BUS STATUS COLORS</h3><div className="manual-grid status-color-grid">{(Object.keys(ST) as S[]).map(status=><label className="color-field status-field" key={status}><span><Icon s={status}/>{ST[status][0]}</span><input type="color" value={colors[status]} onChange={event=>manualStatus(status,event.target.value)}/><code>{colors[status].toUpperCase()}</code></label>)}</div></section></div><div className="settings-actions"><button onClick={()=>applyTheme("default")}>RESET ALL</button><button className="save" onClick={close}>DONE</button></div></section></div>}
function RemoveBusPicker({name,buses,close,remove}:{name:string;buses:B[];close:()=>void;remove:(id:string)=>void}){return <div className="shade remove-shade" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="remove-modal"><div className="mhead"><span>SECTION BUSES<h2>{name}</h2></span><button onClick={close}>X</button></div><div className="remove-list">{buses.length===0?<p>No buses are currently assigned to this section.</p>:buses.map(bus=><div key={bus.id}><span><Icon s={bus.s}/><b>Bus {bus.n||"New"}</b><small>{ST[bus.s][0]}</small></span><button onClick={()=>remove(bus.id)}>REMOVE</button></div>)}</div><div className="settings-actions"><span/><button className="save" onClick={close}>DONE</button></div></section></div>}